Seccion 29(Completa) y 30(Parte 1) - Proyecto bienes raíces
CarlosJCD/Curso-Web pull request #26
Opened 2023-05-06 17:48 UTC by CarlosJCD

Evidencias en codigo del progreso en las secciones 29 y 30 del curso.

2023-05-06 20:01 UTC, CheloChidoone requested changes
@CarlosJCD, no pude correr bien tu proyecto porque no me cargan bien tu css ni js ni algunas de tus imágenes, recuerda que al convertir el proyecto a archivos php para probarlo los admins movemos su carpeta del proyecto a un servidor virtual como Xampp o Wamp y al hacer eso el path que funcionaba para tus archivos cuando eran solo html ya no funciona igual, corrigelo por favor para que lo podamos ver bien.

2023-05-07 07:40 UTC, CheloChidoone approved these changes

2023-05-08 01:35 UTC, CheloChidoone approved these changes

2023-05-08 05:26 UTC, jfer1990 submitted a review, later dismissed
No están cargando los estilos para ninguna página php

2023-05-10 00:19 UTC, merged