Seccion 30 (Parte 2) - Proyecto Bienes Raíces
CarlosJCD/Curso-Web pull request #27
Opened 2023-05-10 06:43 UTC by CarlosJCD

Evidencias en codigo del progreso en la seccion #30 del curso.

2023-05-10 19:39 UTC, CheloChidoone requested changes
@CarlosJCD tienes un error en tu pagina de altas.php, tu validación de la imagen no funciona bien, aparece que no existe la llave 'imagen' que estas buscando en $_FILES, y aunque si seleccionemos una imagen sigue saliendo ese error y la validación falla, también tu campo descripción debería ser una etiqueta textarea y no una etiqueta input para que quede mejor

2023-05-11 06:08 UTC, CheloChidoone approved these changes

2023-05-12 23:00 UTC, jfer1990 requested changes
Carlos, tengo un error al importar tu archivo sql, porfavor correlo y verifica que se importa correctamente en tu workbench y cuando ya funcione lai mportación contigo me lo subes en un nuevo push a este mismo pr, todo lo desmás se ve bien.
Creo que es una situación de versiones de la bd, basicamente no me detecta la etiqueta visible, ya lo revise, todo bien, pero sí trata de usar el workbench primero

2023-05-12 23:16 UTC, jfer1990 approved these changes

2023-05-12 23:40 UTC, merged